version: "3.3"
services:
  python:
    image: mlflow
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "5000:5000"
    environment:
    - AZURE_STORAGE_CONNECTION_STRING="connection-string"
    - STORAGE_URL=storage-url
